Dr 7918 searchagent component style
joblocal/bootstrap pull request #28
Opened 2017-04-11 17:09 UTC by maxstrebel

* Adds search-agent variant
* Opposing to briefing I (for now) only created one variant

2017-04-11 20:45 UTC, jayhof requested changes

2017-04-11 20:45 UTC, jayhof commented on docs/components/search-agent.md
> +          <p class="search-agent-subtitle">Suchagent</p>
I'm not to happy about the naming here, "... subtitle" being mentioned before the "title". Maybe "subtitle" could be "tag" or "byline"

2017-04-11 20:45 UTC, jayhof commented on docs/components/search-agent.md
> +          <h4 class="search-agent-title">Direkt in Deinen Posteingang</h4>
We probably should not use a header tag here.

2017-04-11 20:45 UTC, jayhof commented on docs/components/search-agent.md
> +          <a href="#" class="btn btn-primary">Benachrichtigung anlegen</a>
Could we change the a tag to a button?

2017-04-11 21:14 UTC, maxstrebel commented on docs/components/search-agent.md
> +          <a href="#" class="btn btn-primary">Benachrichtigung anlegen</a>
Agree on the other ones, at this one though, I think as it leads to another page the link might be the right element. Why would you prefer a button? Just so I know how to use it in the future.

2017-04-11 21:16 UTC, maxstrebel commented on docs/components/search-agent.md
> +          <p class="search-agent-subtitle">Suchagent</p>
You're right. I'd go for byline then.

2017-04-12 08:02 UTC, jayhof commented on docs/components/search-agent.md
> +          <a href="#" class="btn btn-primary">Benachrichtigung anlegen</a>
The intent here is not to link to another page but rather trigger an action like showing a modal so the user only has to enter his e-mail address and be done and happy :)

2017-04-13 06:00 UTC, jayhof approved these changes

2017-04-13 07:01 UTC, merged